language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

branches:
  only:
    - master

services:
  - docker

install:
  # starts Docker container
  - cd $TRAVIS_BUILD_DIR/docker
  - docker-compose up -d

#before_script:

script:
  # executes PHPUnit tests
  - docker container exec -it KvnrValidator-php vendor/bin/phpunit -v --debug --stop-on-failure --stop-on-error

after_failure:
  # copy local and Docker logs to /logs DIR
  - sudo mkdir /logs
  - sudo docker container logs php > /logs/docker-container.log
  - sudo cp -a /var/log/php* /logs/
  - sudo chown -R travis:travis /logs

